### ISSUE TITLE
Not able to open app without override security settings

### ISSUE THREAD

**Issue by tomgenoni** [nuance-dev/medio#2]
Would love to try it out but I'm not able to open it on Sequoia 15.1 without disabling security settings.

![Screenshot 2024-11-02 at 12 31 05 PM](https://github.com/user-attachments/assets/922e2c50-1b9e-464f-b4d7-067fed3f06a9)

**Comment by giuliomagnifico** [comment]
I came here to say the same, but if @tomgenoni doesn't have a valid-payed developer account, he can't sign the app.

**Comment by nuance-dev** [comment]
I'm having trouble getting my developer account processed. Been 2 weeks contacting Apple. As soon that's done I'll update the app.

**Comment by Joaov41** [comment]
> I'm having trouble getting my developer account processed. Been 2 weeks contacting Apple. As soon that's done I'll update the app.

If you wish I can sign the up for you with my developer account until you have yours sorted.

**Comment by nuance-dev** [comment]
That'd be nice, thanks!

**Comment by nuance-dev** [comment]
Finally got my Dev account! The last release is notarized, should work fine
